# Generated by Django 3.2.9 on 2021-11-05 04:57

import admission.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternatDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('category', models.CharField(choices=[('7', '7'), ('8', '8'), ('9', '9')], default='7', max_length=70, verbose_name='Выберите класс')),
                ('oblast', models.CharField(choices=[('Нур-Султан', 'Нур-Султан'), (' Алматы', ' Алматы'), ('Шымкент', 'Шымкент'), ('Алматинская область', 'Алматинская область'), ('Акмолинская область', 'Акмолинская область'), ('Атырауская область', 'Атырауская область'), ('Актюбинская область', 'Актюбинская область'), ('Восточно-Казахстанская область', 'Восточно-Казахстанская область'), (' Жамбылская область', ' Жамбылская область'), ('Западно-Казахстанская область', 'Западно-Казахстанская область'), ('Карагандинская область', 'Карагандинская область'), ('Костанайская область', 'Костанайская область'), ('Кызылординская область', 'Кызылординская область'), ('Мангистауская область', 'Мангистауская область'), ('Павлодарская область', 'Павлодарская область'), ('Северо-Казахстанская область', 'Северо-Казахстанская область'), ('Туркестанская область', 'Туркестанская область')], default='Туркестанская область', max_length=100, verbose_name='Область')),
                ('gender', models.CharField(choices=[('мужской', 'мужской'), ('женский', 'женский')], default='мужской', max_length=10, verbose_name='Пол')),
                ('zayavlenye', models.FileField(help_text='Формат файла pdfs', upload_to=admission.models.content_file_name, validators=[admission.models.validate_file_extension])),
                ('copy_svid_rozh', models.FileField(help_text='Формат файла pdfs', upload_to=admission.models.content_file_name, validators=[admission.models.validate_file_extension], verbose_name='Копия свидетельства о рождении')),
                ('copy_vkl_roj_IIN', models.FileField(upload_to=admission.models.content_file_name, validators=[admission.models.validate_file_extension], verbose_name='Копия вкладыша к свидетельству о рождении с указанием ИИН')),
                ('copy_udos_lich', models.FileField(upload_to=admission.models.content_file_name, validators=[admission.models.validate_file_extension], verbose_name='Копия удостоверения личности')),
                ('copy_udos_lich_rod', models.FileField(upload_to=admission.models.content_file_name, validators=[admission.models.validate_file_extension], verbose_name='копия удостоверения личности законных представителей учащегося')),
                ('adress_reg_vseh', models.FileField(upload_to=admission.models.content_file_name, validators=[admission.models.validate_file_extension], verbose_name='Данные по адресу регистрации учащегося и его законных представителей с портала электронного правительства egov.kz')),
                ('copy_prikaz_rab', models.FileField(upload_to=admission.models.content_file_name, validators=[admission.models.validate_file_extension], verbose_name='Копия приказа о принятии на работу, справка с места работы')),
                ('sprv_akima_or_egov', models.FileField(upload_to=admission.models.content_file_name, validators=[admission.models.validate_file_extension], verbose_name='Данные с портала элек. прав. egov.kz или справка акима поселка ...')),
                ('sprv_rab_zrpl_or_mest_ispol_org', models.FileField(upload_to=admission.models.content_file_name, validators=[admission.models.validate_file_extension], verbose_name='Справка с места работы зар. пл.')),
                ('inform_gnpf', models.FileField(upload_to=admission.models.content_file_name, validators=[admission.models.validate_file_extension], verbose_name='Информация о поступлении и движении средств вкладчика единого накопительного пенсионного фонда')),
                ('copy_svd_rozh_mnodet', models.FileField(upload_to=admission.models.content_file_name, validators=[admission.models.validate_file_extension], verbose_name='Справка от многодетных матерей')),
                ('sprv_invd', models.FileField(upload_to=admission.models.content_file_name, validators=[admission.models.validate_file_extension], verbose_name='Справка о инвалидности')),
                ('sprv_asp', models.FileField(upload_to=admission.models.content_file_name, verbose_name='Справка о АСП')),
                ('sprv_neblag_semya', models.FileField(upload_to=admission.models.content_file_name, validators=[admission.models.validate_file_extension], verbose_name='Справка подтверждающую постановку на учет заявителя и его семьи в качестве неблагополучной семьи')),
                ('copy_doc_nepol_semya', models.FileField(upload_to=admission.models.content_file_name, validators=[admission.models.validate_file_extension], verbose_name='Копия документов подтверждающих отсуствие одного из родителей')),
            ],
        ),
    ]
